project:
  name: test_project
  description: 测试项目
  vm:
  - name: dc
    image: YJ-cn_windows_server_2012_r2_x64_dvd_CQV111
    flavor: 2m4g80
    ip_address: 
    - 172.26.4.54/24
    - 172.26.3.27/24
    float_ip: 172.26.4.54
    config_driver: True
  - name: user1
    image: YJ-RuoYi_4.3.0-Centos7
    flavor: 2m4g80
    ip_address:
    - 172.26.3.50/24
    - 172.26.5.45/24
    config_driver: True
  - name: user2
    image: YJ-Ubuntu-20.04-base-cloud
    flavor: 2m4g80
    ip_address:
    - 172.26.5.100/24
    config_driver: True



      