project:
  name: test_proj
  vm:
  - name: vm-1
    image: Centos7-test-2003
    flavor: yj.2_2_80
    ip_addr: 192.168.1.101/24
  - name: vm-2
    image: Centos7-test-2003
    flavor: yj.2_2_80
    ip_addr: 192.168.1.102/24
